// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List active products in the Rexovaan Shoppie store, with stock, price and short code.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive substring to match product name."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("bot_products").select("id,name,short_code,price,currency,last_known_stock,is_active").eq("is_active", true).order("sort_order", { ascending: true }).limit(limit ?? 25);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Get full details for a single product by short_code or id.",
  inputSchema: {
    code: z2.string().describe("Product short_code (preferred) or UUID id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ code }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const isUuid = /^[0-9a-f-]{36}$/i.test(code);
    const { data, error } = await supabase.from("bot_products").select("id,name,short_code,description,price,currency,last_known_stock,is_active,delivery_instruction").eq(isUuid ? "id" : "short_code", code).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/my-account.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var my_account_default = defineTool3({
  name: "my_account",
  title: "My account",
  description: "Get the signed-in customer's balance, pay-later limit and referral balance.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("bot_customers").select("first_name,username,balance,pay_later_limit,pay_later_used,pay_later_enabled,referral_balance").eq("auth_user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Customer profile not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { account: data }
    };
  }
});

// src/lib/mcp/tools/my-orders.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var my_orders_default = defineTool4({
  name: "my_orders",
  title: "My orders",
  description: "List the signed-in customer's recent orders.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max rows to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: customer } = await supabase.from("bot_customers").select("id").eq("auth_user_id", ctx.getUserId()).maybeSingle();
    if (!customer) {
      return { content: [{ type: "text", text: "Customer profile not found" }], isError: true };
    }
    const { data, error } = await supabase.from("bot_orders").select("id,product_name,quantity,total_price,status,source,created_at,delivered_at").eq("customer_id", customer.id).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { orders: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eygkdpfjrjwwbiackfpr";
var mcp_default = defineMcp({
  name: "rexovaan-shoppie-mcp",
  title: "Rexovaan Shoppie",
  version: "0.1.0",
  instructions: "Tools for the Rexovaan Shoppie store. Use `list_products` and `get_product` to browse the catalog (public). Use `my_account` and `my_orders` to read the signed-in customer's own balance and order history.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_product_default, my_account_default, my_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
