// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eygkdpfjrjwwbiackfpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5Z2tkcGZqcmp3d2JpYWNrZnByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA1NjkyMzEsImV4cCI6MjA5NjE0NTIzMX0.KQQkvoNmrXROOEHzSsePcyvpDEmbrueNEmtnvJlZ-dU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});